Lab09/Lab06/Components/CartSummaryViewComponent.cs
using Lab06.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab06.Components
{
    public class CartSummaryViewComponent: ViewComponent
    {

        private Cart cart;

        public CartSummaryViewComponent(Cart cart)
        {
            this.cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }

    }
}

Lab09/Lab06/Components/NavigationMenuViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lab06.Models;

namespace Lab06.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IParkRangerRepository repository;

        public NavigationMenuViewComponent(IParkRangerRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["state"];
            return View(repository.ParkRangers
                .Select(x => x.State)
                .Distinct()
                .OrderBy(x => x));
        }

    }
}

Lab09/Lab06/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lab06.Infrustructure;
using Lab06.Models;
using Lab06.Models.ViewModels;


namespace SportsStore.Controllers
{
    public class CartController : Controller
    {

        private IParkRangerRepository repo;
        private Cart cart;

        public CartController(IParkRangerRepository repo, Cart cart)
        {
            this.repo = repo;
            this.cart = cart;
        }

        public ViewResult Index(string returnURL)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnURL = returnURL
            });
        }

        public RedirectToActionResult AddToCart(int parkRangerId, string returnURL)
        {
            ParkRanger parkRanger = repo.ParkRangers
                .FirstOrDefault(pr => pr.ParkRangerId == parkRangerId);

            if (parkRanger != null)
            {
                cart.AddItem(parkRanger, 1);
            }

            return RedirectToAction("Index", new { returnURL });
        }

        public RedirectToActionResult RemoveFromCart(int parkRangerId, string returnURL)
        {
            ParkRanger parkRanger = repo.ParkRangers
                .FirstOrDefault(pr => pr.ParkRangerId == parkRangerId);

            if (parkRanger != null)
            {
                cart.RemoveLine(parkRanger);
            }

            return RedirectToAction("Index", new { returnURL });

        }
    }
}

Lab09/Lab06/Views/Shared/ParkRangerSummary.cshtml
@model ParkRanger

<div class="well">
    <h3>
        <strong>@Model.LastName, @Model.FirstName</strong>
        <span class="pull-right label label-primary">
            <strong>Bachelors Degree? : </strong>
            @Model.BachelorDegree
        </span>
    </h3>

    <form id="@Model.ParkRangerId" asp-action="AddToCart"
        asp-controller="Cart" method="post">

        <input type="hidden" asp-for="ParkRangerId" />
        <input type="hidden" name="returnURL"
               value="@ViewContext.HttpContext.Request.PathAndQuery()"/>

        <span class="lead">
            @Model.State
            <button type="submit" class="btn btn-success btn-sm pull-right">
                Add To Hiring List
            </button>
        </span>
    </form>

</div>

Lab09/Lab06/Views/Shared/StateParkSummary.cshtml
@model StatePark

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">
            @Model.State
        </span>
    </h3>

    <span class="lead"> @Model.Address</span>

</div>

Lab09/Lab06/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>State Parks</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">State Park Info</a>

        <div class="pull-right">
            @await Component.InvokeAsync("CartSummary");
        </div>

    </div>

    <div class="row panel">
        <div id="categories" class="col-xs-3">
            <p>
                Welcome to the State Park finder!
                Within this website you can find hundreds of <a href="https://localhost:5001/StatePark/List">State Parks</a>
                or <a href="https://localhost:5001/ParkRanger/List">Park Rangers</a>
            </p>
            @await Component.InvokeAsync("NavigationMenu");
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>


</body>
</html>