Lab11/Lab06/Models/Cart.cs
using Lab06.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab06.Models
{
    public class Cart
    {
        private List<CartLine> lineCollection = new List<CartLine>();

        public virtual void AddItem(ParkRanger parkRanger, int quantity)
        {
            CartLine line = lineCollection
                .Where(pr => pr.ParkRanger.ParkRangerId == parkRanger.ParkRangerId)
                .FirstOrDefault();

            if (line == null)
            {
                lineCollection.Add(new CartLine
                {
                    ParkRanger = parkRanger,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }


        public virtual void RemoveLine(ParkRanger parkRanger) =>
            lineCollection.RemoveAll(l => l.ParkRanger.ParkRangerId == parkRanger.ParkRangerId);

        public virtual decimal ComputeTotalValue() =>
            lineCollection.Sum(e => e.Quantity);

        public virtual void Clear() => lineCollection.Clear();

        public virtual IEnumerable<CartLine> Lines => lineCollection;
    }

    public class CartLine
    {
        public int CartLineId { get; set; }
        public ParkRanger ParkRanger { get; set; }
        public int Quantity { get; set; }
    }

}

Lab11/Lab06/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lab06.Infrustructure;
using Lab06.Models;
using Lab06.Models.ViewModels;


namespace SportsStore.Controllers
{
    public class CartController : Controller
    {

        private IParkRangerRepository repo;
        private Cart cart;

        public CartController(IParkRangerRepository repo, Cart cart)
        {
            this.repo = repo;
            this.cart = cart;
        }

        public ViewResult Index(string returnURL)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnURL = returnURL
            });
        }

        public RedirectToActionResult AddToCart(int parkRangerId, string returnURL)
        {
            ParkRanger parkRanger = repo.ParkRangers
                .FirstOrDefault(pr => pr.ParkRangerId == parkRangerId);

            if (parkRanger != null)
            {
                cart.AddItem(parkRanger, 1);
            }

            return RedirectToAction("Index", new { returnURL });
        }

        public RedirectToActionResult RemoveFromCart(int parkRangerId, string returnURL)
        {
            ParkRanger parkRanger = repo.ParkRangers
                .FirstOrDefault(pr => pr.ParkRangerId == parkRangerId);

            if (parkRanger != null)
            {
                cart.RemoveLine(parkRanger);
            }

            return RedirectToAction("Index", new { returnURL });

        }
    }
}

Lab11/Lab06/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lab06.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Lab06.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository orderRepo;
        private Cart cart;

        public OrderController(IOrderRepository orderRepo, Cart cart)
        {
            this.orderRepo = orderRepo;
            this.cart = cart;
        }

        [Authorize]
        public ViewResult List() =>
            View(orderRepo.Orders.Where(o => !o.Contacted));

        [HttpPost]
        [Authorize]
        public IActionResult MarkContacted(int orderId)
        {
            Order order = orderRepo.Orders
                .FirstOrDefault(o => o.OrderId == orderId);

            if(order != null)
            {
                order.Contacted = true;
                orderRepo.SaveOrder(order);
            }

            return RedirectToAction(nameof(List));


        }


        public IActionResult Checkout() => View(new Order());


        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if(cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry your cart is empty");
            }

            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                orderRepo.SaveOrder(order);
                return RedirectToAction(nameof(Completed));
            }

            return View(order);

        }

        public ViewResult Completed()
        {
            cart.Clear();
            return View();
        }

    }

}

Lab11/Lab06/Views/Cart/Index.cshtml
@model CartIndexViewModel

<h2>Hiring List</h2>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th class="text-right">Bachelor Degree?</th>
            <th class="text-right">State</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
        <tr>
            <td class="text-center">@line.Quantity</td>
            <td class="text-left">@line.ParkRanger.FirstName</td>
            <td class="text-left">@line.ParkRanger.LastName</td>
            <td class="text-right">@line.ParkRanger.BachelorDegree</td>
            <td class="text-right">@line.ParkRanger.State</td>
            <td>
                <form asp-action="RemoveFromCart" method="post">
                    <input type="hidden" name="ParkRangerId" value="@line.ParkRanger.ParkRangerId" />
                    <input type="hidden" name="returnURL" value="@Model.ReturnURL" />
                    <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                </form>
            </td>



        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total Employees:</td>
            <td class="text-right">@Model.Cart.ComputeTotalValue()</td>
        </tr>
    </tfoot>
</table>


<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnURL">Continue Shopping</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Order">Checkout</a>
</div>